### ISSUE TITLE
blank.png

### ISSUE THREAD

**Issue by jthandy** [fishtown-analytics/fishtown-analytics.github.io#1]
For some reason the page is getting a 404 when trying to find blank.png. There’s some weird stuff going on as a part of the jekyll asset pipeline that I can’t figure out because blank.png is actually there in the source image folder. It’s dumb and nitpicky but I’d rather clean it up while the site is brand new.

**Comment by somegoodpixels** [comment]
that's fixed now.

**Comment by jthandy** [comment]
verified good to go. thanks!!
