### ISSUE TITLE
form submission error message

### ISSUE THREAD

**Issue by jthandy** [fishtown-analytics/fishtown-analytics.github.io#2]
The form actually works—it submits correctly to formspree and I get the email in my inbox, which is great. However, it shows an error message on the screen when you submit it. I haven’t dug into this error message; would be great if you could. This is actually an issue for sharing the site with the world…looks like the email didn’t go through when it did.

**Comment by somegoodpixels** [comment]
Hmm — I didn't know that the theme came with those helpers. I just modified
the timber js file to look for the right response. Formspree formatted the
JSON response differently than it was expecting.

**Comment by jthandy** [comment]
tested; works. thanks!!
