### ISSUE TITLE
The image at the top of the page doesn't load on retina displays

### ISSUE THREAD

**Issue by jthandy** [fishtown-analytics/fishtown-analytics.github.io#3]
There's some timber thing going on that tries to load the same image name but with `@2x`...so `fishtown_street@2x.jpg`. Need to either change that within timber, or upload a second image. I tried the latter but for some reason it didn't work.

**Comment by drewbanin** [comment]
Fixed this. I don't have a retina display, but it looks like it works when emulated through google dev tools. Please confirm and close!

**Comment by jthandy** [comment]
great!
